/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	'/health': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Health Check
		 * @description Health check endpoint that works without external dependencies.
		 *
		 *     Returns:
		 *         Status dictionary indicating service health
		 */
		get: operations['health_check_health_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/assets/ingest': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Ingest Assets
		 * @description Scan filesystem and ingest images.
		 *
		 *     Args:
		 *         request: Ingest request with path and options
		 *         db: Database session
		 *
		 *     Returns:
		 *         Ingest response with counts
		 *
		 *     Raises:
		 *         HTTPException: If path doesn't exist or is not a directory
		 */
		post: operations['ingest_assets_api_v1_assets_ingest_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/assets': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * List Assets
		 * @description List assets with pagination and optional date filters.
		 *
		 *     Args:
		 *         page: Page number (1-indexed)
		 *         page_size: Number of items per page
		 *         from_date: Optional start date filter (ISO format)
		 *         to_date: Optional end date filter (ISO format)
		 *         db: Database session
		 *
		 *     Returns:
		 *         Paginated response with assets
		 */
		get: operations['list_assets_api_v1_assets_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/assets/{asset_id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Asset
		 * @description Get a single asset by ID.
		 *
		 *     Args:
		 *         asset_id: Asset ID
		 *         db: Database session
		 *
		 *     Returns:
		 *         Asset details
		 *
		 *     Raises:
		 *         HTTPException: If asset not found
		 */
		get: operations['get_asset_api_v1_assets__asset_id__get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/search': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Search Assets
		 * @description Semantic search for assets using text query.
		 *
		 *     Args:
		 *         request: Search request with query and filters
		 *         db: Database session
		 *         qdrant: Qdrant client for vector search
		 *
		 *     Returns:
		 *         Search response with matching assets and scores
		 *
		 *     Raises:
		 *         HTTPException: If Qdrant is unavailable or embedding fails
		 */
		post: operations['search_assets_api_v1_search_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		/**
		 * Asset
		 * @description Asset response schema.
		 */
		Asset: {
			/** Id */
			id: number;
			/** Path */
			path: string;
			/**
			 * Createdat
			 * Format: date-time
			 */
			createdAt: string;
			/** Indexedat */
			indexedAt?: string | null;
		};
		/**
		 * ErrorResponse
		 * @description Error response schema.
		 */
		ErrorResponse: {
			/** Error */
			error: string;
			/** Message */
			message: string;
			/** Details */
			details?: {
				[key: string]: string;
			} | null;
		};
		/** HTTPValidationError */
		HTTPValidationError: {
			/** Detail */
			detail?: components['schemas']['ValidationError'][];
		};
		/**
		 * IngestRequest
		 * @description Request to ingest images from filesystem.
		 */
		IngestRequest: {
			/** Rootpath */
			rootPath: string;
			/**
			 * Recursive
			 * @default true
			 */
			recursive: boolean;
			/**
			 * Extensions
			 * @default [
			 *       "jpg",
			 *       "jpeg",
			 *       "png",
			 *       "webp"
			 *     ]
			 */
			extensions: string[];
			/**
			 * Dryrun
			 * @default false
			 */
			dryRun: boolean;
		};
		/**
		 * IngestResponse
		 * @description Response from ingest operation.
		 */
		IngestResponse: {
			/** Discovered */
			discovered: number;
			/** Enqueued */
			enqueued: number;
			/** Skipped */
			skipped: number;
		};
		/** PaginatedResponse[Asset] */
		PaginatedResponse_Asset_: {
			/** Items */
			items: components['schemas']['Asset'][];
			/** Total */
			total: number;
			/** Page */
			page: number;
			/** Pagesize */
			pageSize: number;
			/** Hasmore */
			hasMore: boolean;
		};
		/**
		 * SearchRequest
		 * @description Request to search for assets.
		 */
		SearchRequest: {
			/** Query */
			query: string;
			/**
			 * Limit
			 * @default 50
			 */
			limit: number;
			/**
			 * Offset
			 * @default 0
			 */
			offset: number;
			/** Filters */
			filters?: {
				[key: string]: string;
			} | null;
		};
		/**
		 * SearchResponse
		 * @description Response from search operation.
		 */
		SearchResponse: {
			/** Results */
			results: components['schemas']['SearchResult'][];
			/** Total */
			total: number;
			/** Query */
			query: string;
		};
		/**
		 * SearchResult
		 * @description Single search result with asset and score.
		 */
		SearchResult: {
			asset: components['schemas']['Asset'];
			/** Score */
			score: number;
			/**
			 * Highlights
			 * @default []
			 */
			highlights: string[];
		};
		/** ValidationError */
		ValidationError: {
			/** Location */
			loc: (string | number)[];
			/** Message */
			msg: string;
			/** Error Type */
			type: string;
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
	health_check_health_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						[key: string]: string;
					};
				};
			};
		};
	};
	ingest_assets_api_v1_assets_ingest_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['IngestRequest'];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['IngestResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	list_assets_api_v1_assets_get: {
		parameters: {
			query?: {
				page?: number;
				page_size?: number;
				from_date?: string | null;
				to_date?: string | null;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['PaginatedResponse_Asset_'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	get_asset_api_v1_assets__asset_id__get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				asset_id: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Asset'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	search_assets_api_v1_search_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['SearchRequest'];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['SearchResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
			/** @description Service Unavailable */
			503: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
}
